name: Deployment Pipeline
on:
  push:
    branches: 
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build
        run: npm ci
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_BIBLE_ID: ${{ secrets.REACT_APP_BIBLE_ID }}
      - name: deploy
        run: npm run deploy
